<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_rathieshmacappstudio.com</name>
   <tag></tag>
   <elementGuidId>53243905-dee2-4c07-9b44-5cb7e0c4ccdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.user-name.drop-down-option</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav_menu']/ul/li[7]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>57e3c08e-cc4c-4e94-a17d-cd2e253ce27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>user-name drop-down-option</value>
      <webElementGuid>073368b2-67d0-44b3-9879-938ea6362bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button-active</name>
      <type>Main</type>
      <value>data-button-active</value>
      <webElementGuid>c9e22013-dc96-433a-b2d8-3cc02b71bace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>rathiesh@macappstudio.com</value>
      <webElementGuid>7059d2a7-f122-4266-b1e9-8f602528e72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav_menu&quot;)/ul[@class=&quot;nav-list&quot;]/li[@class=&quot;nav-items&quot;]/div[@class=&quot;profile-dropdown-box&quot;]/div[@class=&quot;name-profile-pic-set&quot;]/button[@class=&quot;user-name drop-down-option&quot;]</value>
      <webElementGuid>218d1601-001a-4071-be00-d5c019e4c317</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav_menu']/ul/li[7]/div/div/button</value>
      <webElementGuid>5644a18e-8d51-4a63-9bca-11d458098051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::button[1]</value>
      <webElementGuid>f6d9cd04-9cc0-4001-a947-9bc6e7c2c477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::button[1]</value>
      <webElementGuid>37b1e7e3-e2a2-41a2-bc91-0805457a2855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[1]/preceding::button[1]</value>
      <webElementGuid>755e36b2-afd1-41d0-ab4a-2100149e58bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Dashboard'])[1]/preceding::button[1]</value>
      <webElementGuid>3a56262a-4d5b-485f-a014-56d49eda1f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='rathiesh@macappstudio.com']/parent::*</value>
      <webElementGuid>a4dc2e2a-b692-473c-bdcb-208a738d95e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div/div/button</value>
      <webElementGuid>0e78adf6-8c2a-496d-bf86-f6a2b6301e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'rathiesh@macappstudio.com' or . = 'rathiesh@macappstudio.com')]</value>
      <webElementGuid>ff70108f-c4c8-41ca-856d-5ee67fc481de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
