<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Allow all</name>
   <tag></tag>
   <elementGuidId>3bcedca2-e770-4dec-bd67-4cbadabafbdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5299f370-da77-4b7f-8847-94bedc596984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll</value>
      <webElementGuid>ae9bbd99-cdb7-4d35-9594-0295bf232108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CybotCookiebotDialogBodyButton</value>
      <webElementGuid>1824493d-1f1b-437c-b343-419eba7a10b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>280c3cbd-f9b4-4108-8f33-421822aaf26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>272aa06e-b8cf-4d57-b0a0-cfaf09a3708e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Allow all</value>
      <webElementGuid>8b3c95e7-9051-423f-8aa1-27c31f415085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll&quot;)</value>
      <webElementGuid>f46bdad8-c382-43e0-9d83-04ad52b95edf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll']</value>
      <webElementGuid>946adcda-2cef-4a22-992e-dc2f89e711f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CybotCookiebotDialogBodyButtonsWrapper']/button[4]</value>
      <webElementGuid>1a0a7106-1185-4856-81a8-75474af4ee36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customize'])[1]/following::button[1]</value>
      <webElementGuid>5f8add79-b42d-4238-8f01-0bb20dbdea86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow selection'])[1]/following::button[2]</value>
      <webElementGuid>f129e9a2-ba60-4914-98eb-0f7e7c297981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookiebot by Usercentrics'])[1]/preceding::button[1]</value>
      <webElementGuid>5e7f05b3-9a49-40a4-b661-c5563dbc7200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Allow all']/parent::*</value>
      <webElementGuid>d8ba0ede-51b3-40c7-aba2-86e30837dfa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>5b7cd988-4a28-4ca9-a350-734bc9d98838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll' and (text() = 'Allow all' or . = 'Allow all')]</value>
      <webElementGuid>e577c061-28ab-40b1-84a5-963972f4110b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
