<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_remember_me_check</name>
   <tag></tag>
   <elementGuidId>8f376239-9e28-40c8-b657-05c69e96f9aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#remember_me_check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='remember_me_check']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d31cbff-5dad-4a25-a4e7-eb2c72266bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f91d4161-9588-47ed-98ee-1201ea61b3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check-box</value>
      <webElementGuid>d9ebb076-9402-4e5f-a622-73bba98736e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remember_me_check</value>
      <webElementGuid>2dd9cf69-ab1b-4e44-8422-323562d4efe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remember_me_check&quot;)</value>
      <webElementGuid>729e06b4-0ebc-4284-b77c-60017fc9303b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='remember_me_check']</value>
      <webElementGuid>ad0ada2c-dca5-4e99-b344-f17c768df4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login_box']/div[3]/label/input</value>
      <webElementGuid>7c733909-d6b0-4dbf-b230-1ddc26f86258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>7ea3f5ac-dd7a-4723-bdee-4ef85f2f9c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'remember_me_check']</value>
      <webElementGuid>91d29931-72f6-43ed-bf0e-021a3ea058cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
