<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_UsernameEmail Address</name>
   <tag></tag>
   <elementGuidId>ba7759d9-5476-4d6d-872a-feed76b75928</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-items</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login_box']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c51effba-c124-415b-b035-7ab7f6d71526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-items</value>
      <webElementGuid>0582d818-78e8-4a1d-982f-0e03e3840c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username/Email Address</value>
      <webElementGuid>f4058aec-7e6d-4007-b9c1-d27de97e2161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_box&quot;)/div[@class=&quot;form-group-set&quot;]/div[@class=&quot;form-items&quot;]</value>
      <webElementGuid>028872e7-30ac-44bb-a000-dff56841bde2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login_box']/div[2]/div</value>
      <webElementGuid>633d7599-7a98-480d-8edc-861ce3c0ce20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/following::div[2]</value>
      <webElementGuid>311325eb-f466-42fa-87d9-f71051086a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create a free account'])[1]/following::div[11]</value>
      <webElementGuid>354ed87c-46dd-4485-9307-5528d349ad99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::div[3]</value>
      <webElementGuid>c69398ee-51f4-4acc-aebf-79256e5444f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[3]/preceding::div[5]</value>
      <webElementGuid>53c623d9-3c65-45bc-b4a6-0e1aa32857f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/div/div[3]/div/div[2]/div</value>
      <webElementGuid>0c7bbed0-3446-438f-b600-17cbe916e4c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Username/Email Address' or . = 'Username/Email Address')]</value>
      <webElementGuid>e3edc1fb-e663-4fd7-8cab-6bf2bf0eb35f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
