<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_remember_me_check</name>
   <tag></tag>
   <elementGuidId>fce667f1-ad31-442b-92e0-31c01a94fc10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#remember_me_check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='remember_me_check']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56c0c616-f2eb-4394-92df-00fa2043766b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1117d6e3-a00b-4c14-957d-82d66cae300c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check-box</value>
      <webElementGuid>d432b38f-fb51-4640-afd7-559c5eda74ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remember_me_check</value>
      <webElementGuid>cc4d3f21-3794-48ac-9acb-70796ea9b8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remember_me_check&quot;)</value>
      <webElementGuid>bd07454d-90a3-40a1-8c77-ea1376b7980d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='remember_me_check']</value>
      <webElementGuid>d5c08401-380b-40d2-a4aa-3d4878ea108b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login_box']/div[3]/label/input</value>
      <webElementGuid>582c0c9c-6bf6-4189-bc65-28c0747fc977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>052f8977-e09d-48f2-b938-6480784067bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'remember_me_check']</value>
      <webElementGuid>a3bbd5b6-763e-4ff8-9693-eb04c8e870cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
