<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_rathieshmacappstudio.com</name>
   <tag></tag>
   <elementGuidId>edc7acd9-82d8-4664-ad11-7d99dfdf37e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.user-name.drop-down-option</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav_menu']/ul/li[7]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3e3c73c-2386-4cf5-857c-b0dfcbe8eb3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>user-name drop-down-option</value>
      <webElementGuid>30097238-9d5f-49c2-9fdb-59d690c8e3e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button-active</name>
      <type>Main</type>
      <value>data-button-active</value>
      <webElementGuid>717372e4-69aa-4d2e-9a90-11513fc9762e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>rathiesh@macappstudio.com</value>
      <webElementGuid>ab7f3262-71be-4e6e-abf9-5efb0c6951a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav_menu&quot;)/ul[@class=&quot;nav-list&quot;]/li[@class=&quot;nav-items&quot;]/div[@class=&quot;profile-dropdown-box&quot;]/div[@class=&quot;name-profile-pic-set&quot;]/button[@class=&quot;user-name drop-down-option&quot;]</value>
      <webElementGuid>432de784-e727-4776-a447-ae30c4c31a98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav_menu']/ul/li[7]/div/div/button</value>
      <webElementGuid>e80b1687-dfe7-407a-8222-e2b362c9f3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::button[1]</value>
      <webElementGuid>ee4d9af8-6d2e-48c0-94bf-6dd2e5086fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::button[1]</value>
      <webElementGuid>e81d4bc2-4a26-4303-8f7b-be8de2b7a1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[1]/preceding::button[1]</value>
      <webElementGuid>00d06695-dbcc-426e-87ad-2366e1ef5890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Dashboard'])[1]/preceding::button[1]</value>
      <webElementGuid>d936ffdf-1abf-4534-a48d-09a288565301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='rathiesh@macappstudio.com']/parent::*</value>
      <webElementGuid>138f22d6-df37-4331-84b0-c776541ba410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div/div/button</value>
      <webElementGuid>317cc2b2-6975-46fe-af46-c0c211bf5de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'rathiesh@macappstudio.com' or . = 'rathiesh@macappstudio.com')]</value>
      <webElementGuid>5fe2460b-8b65-4dfc-96d6-605a1a3a6ae9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
