<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_remember_me_check</name>
   <tag></tag>
   <elementGuidId>446a31ab-76c1-4f09-8c10-892c67a0ee42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#remember_me_check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='remember_me_check']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3cf006f3-446b-4b92-9b65-cc5ebe4e2ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4f83cc79-ecca-4729-8610-55737d3a1745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check-box</value>
      <webElementGuid>6d351148-a764-4dcf-b27e-df748decb944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remember_me_check</value>
      <webElementGuid>ece400dd-6f59-4aeb-90e4-9c854444f994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remember_me_check&quot;)</value>
      <webElementGuid>5db9d760-fa52-458b-9346-9f58971ecd68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='remember_me_check']</value>
      <webElementGuid>1b0c938b-b31f-4931-8617-987ea0ab0c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login_box']/div[3]/label/input</value>
      <webElementGuid>7cc39b1d-be03-4004-8fb6-3f045a491ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>348ae03d-5968-4a7a-bac0-6a3128d73671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'remember_me_check']</value>
      <webElementGuid>0c836bdb-2ba8-40a6-a05f-baa04efe44f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
