<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>e97fdf59-9bd6-4061-8c34-5acbd02e5c63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#open_login_modal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='open_login_modal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>512c48e6-5088-4247-8654-333dc3fb5afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-lg btn-pill btn-wide</value>
      <webElementGuid>2c5fc9bf-27ff-4d4c-91b4-424ea431e2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>open_login_modal</value>
      <webElementGuid>94bd9257-8c77-427e-9846-df12eb40dba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>d644540a-08a2-444c-9e6f-b7b1ea5dbc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;open_login_modal&quot;)</value>
      <webElementGuid>a2435460-e8e1-45ed-af28-2953fe410675</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='open_login_modal']</value>
      <webElementGuid>b961fccd-d557-4521-9948-1c351ae89a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav_menu']/ul/li[6]/button</value>
      <webElementGuid>4e548f63-962c-448c-9d4f-f569f96c4583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::button[1]</value>
      <webElementGuid>9273ca51-4083-4bb1-9ac1-bfde31903859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::button[1]</value>
      <webElementGuid>6b2d597c-ffe4-4397-9609-03e26c571cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create a free account'])[1]/preceding::button[1]</value>
      <webElementGuid>a8f300bf-2d9f-437e-9707-7d9c8f7c1f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>705a67f3-f1d0-4586-ad31-09b357a134db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/button</value>
      <webElementGuid>abfabee2-6771-47ef-a102-21ef7bc7d7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'open_login_modal' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>28f247e6-3cc7-43fe-8958-cbd6eaed2ca8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
