<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_remember_me_check</name>
   <tag></tag>
   <elementGuidId>6342e47d-fb7a-4e56-bb44-99d20e75822c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#remember_me_check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='remember_me_check']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5dd3dfb5-e27c-4c01-aac8-2f892547e9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8b04f113-3b89-4c39-b931-77d7e97be6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check-box</value>
      <webElementGuid>41768eb9-4067-4c43-9992-611b93c83977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remember_me_check</value>
      <webElementGuid>6d76086f-1f03-4062-92a1-acc95beba002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remember_me_check&quot;)</value>
      <webElementGuid>f4d532ee-ba29-4963-9b12-0a75d1b85eff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='remember_me_check']</value>
      <webElementGuid>a6e9aa91-9a05-4f08-b8dd-83cc33cfc8f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login_box']/div[3]/label/input</value>
      <webElementGuid>3294a37a-1d84-498a-a45f-cb1999875650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>3384a8e6-5088-4ef9-88b4-7101372e0380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'remember_me_check']</value>
      <webElementGuid>00e6bbd5-8d53-4791-9c87-c873bd31eefd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
