<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Logout</name>
   <tag></tag>
   <elementGuidId>972bd213-67cc-4323-b8b2-1e79483e282b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.logout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav_menu']/ul/li[9]/div/div[2]/ul/li[4]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>dd13e4f1-f629-47a5-bce4-4136d51e2ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logout</value>
      <webElementGuid>3ddc0174-a554-4ba1-b4cc-a514740124f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>3a805871-8600-473c-9409-083dfed38efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav_menu&quot;)/ul[@class=&quot;nav-list&quot;]/li[@class=&quot;nav-items&quot;]/div[@class=&quot;profile-dropdown-box&quot;]/div[@class=&quot;prof-dropdown-list&quot;]/ul[@class=&quot;dropdown-list cust-prof-nav-dropdown&quot;]/li[@class=&quot;dropdown-items&quot;]/p[@class=&quot;logout&quot;]</value>
      <webElementGuid>b36b6b65-418a-42c2-af06-817a5b0610de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav_menu']/ul/li[9]/div/div[2]/ul/li[4]/p</value>
      <webElementGuid>40ea8094-a2c6-41d0-8324-610f7bee8541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Dashboard'])[1]/following::p[1]</value>
      <webElementGuid>139408b0-d325-4875-a960-74fa4b9cdcb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[1]/following::p[1]</value>
      <webElementGuid>1a175361-db90-4bd8-910d-80ace83d3c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popular Services'])[1]/preceding::p[2]</value>
      <webElementGuid>1e5037ab-12fd-4c09-b009-2ae95154fe6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>15c45367-fd35-4106-b77d-b0fed30121de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/p</value>
      <webElementGuid>1be1aa9d-f85c-44d4-a85d-f942092427ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>0bc7c056-7207-4cca-b7e8-c48a01005b84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
