<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Create a free account_close-icon</name>
   <tag></tag>
   <elementGuidId>189bdbb9-185e-4211-9df9-66b3b3b640b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.close-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login_modal']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2709b8ea-452c-4c78-83df-af990ccd1613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./static/media/close-login.80fba7f1f732a18570b0ab99a5755bb6.svg</value>
      <webElementGuid>1a4f48c3-d333-4541-aaf4-88c20e71653a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>a1d91220-ab07-44da-8800-c9a4627a6c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-icon</value>
      <webElementGuid>15bd61ef-6174-4173-ab85-187981a11575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_modal&quot;)/div[@class=&quot;login-modal open&quot;]/img[@class=&quot;close-icon&quot;]</value>
      <webElementGuid>1608e664-df5c-4cc5-8360-e43a8105f333</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login_modal']/div/img</value>
      <webElementGuid>90121019-3f83-4bc1-b772-14848fa6d91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='logo'])[3]</value>
      <webElementGuid>7fbfe96b-7c43-44d6-b3b3-cf16bf41899e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/img</value>
      <webElementGuid>6690d467-c725-437c-b8bd-5e0cf03d42ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './static/media/close-login.80fba7f1f732a18570b0ab99a5755bb6.svg' and @alt = 'logo']</value>
      <webElementGuid>e16b36dd-caa5-4b5f-815a-e8463a0ed7a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
