<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_remember_me_check</name>
   <tag></tag>
   <elementGuidId>4cec1dd5-fd74-4dc0-9c31-2fb01027033e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#remember_me_check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='remember_me_check']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0d99753-f011-4643-852e-742459f19cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cd211012-f452-406c-8498-08031b4554fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check-box</value>
      <webElementGuid>70957f8f-4b95-4696-b152-df7b03da810a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remember_me_check</value>
      <webElementGuid>029916c1-8fc0-40ce-b491-861e8ba805d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remember_me_check&quot;)</value>
      <webElementGuid>278d7a51-d6a1-48fc-8f59-29be100fd35c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='remember_me_check']</value>
      <webElementGuid>a5793e76-4cbc-466e-b298-975e7553fccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login_box']/div[3]/label/input</value>
      <webElementGuid>9f55159b-d3ec-4cf8-b6eb-d9e5fa6b1fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>5ed041dc-e606-4fd7-a6c0-91ba17e6ea50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'remember_me_check']</value>
      <webElementGuid>2006e4f2-1ff3-46dd-8a6e-f645d624f4ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
