<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Invalid Credentials or activate account</name>
   <tag></tag>
   <elementGuidId>c53dcadf-b92f-46f7-bb52-7458eca75658</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login_box']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b4295b87-c82f-43df-9a6d-4fca48b32ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>cbd4b0be-96e4-45c2-a7ed-732c9fa44a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Credentials or activate account</value>
      <webElementGuid>921bb6bc-34e0-4fe8-a0c0-2b7d833769b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_box&quot;)/p[@class=&quot;error&quot;]</value>
      <webElementGuid>0e1dcae4-6b38-4474-95ab-8eee34096b37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login_box']/p</value>
      <webElementGuid>de6e5ce7-3e19-4cc4-be78-757fb9cc4c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/following::p[1]</value>
      <webElementGuid>41f50f5c-1648-4d88-ac3b-51cadf7579a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/following::p[5]</value>
      <webElementGuid>753330c6-9a26-4e30-8ea3-114b28981769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[3]/preceding::p[1]</value>
      <webElementGuid>ff9273a8-aa79-4b0e-8cff-dcc2ea173942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invalid Credentials or activate account']/parent::*</value>
      <webElementGuid>1f07b5eb-7a34-4c6b-a641-177eac72d823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/p</value>
      <webElementGuid>7c52efba-91ba-4284-9317-3238f9b1810e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Invalid Credentials or activate account' or . = 'Invalid Credentials or activate account')]</value>
      <webElementGuid>4f6b19a2-8d2b-446e-ba9c-ba0174a534c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
