<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Create a free account_close-icon</name>
   <tag></tag>
   <elementGuidId>a6f572d2-2215-44d0-9d0f-340cde73ca3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.close-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login_modal']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>694ed163-32dd-48aa-bec7-c02866fedd7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./static/media/close-login.80fba7f1f732a18570b0ab99a5755bb6.svg</value>
      <webElementGuid>848bbdbb-a4cf-4490-9427-82d4e4cb478b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>35633a39-f795-4550-a684-288a61836a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-icon</value>
      <webElementGuid>d6a91fdc-f946-4c1b-ad7a-cd002e48b9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_modal&quot;)/div[@class=&quot;login-modal open&quot;]/img[@class=&quot;close-icon&quot;]</value>
      <webElementGuid>95337360-427c-4c35-9119-3e4342abf4e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login_modal']/div/img</value>
      <webElementGuid>045f2461-458a-4720-9939-5d2d01ff90ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='logo'])[3]</value>
      <webElementGuid>20112654-a433-4eb4-ba47-d9bc3473eb0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/img</value>
      <webElementGuid>cb12d66f-5aee-46bd-8483-e936d6b8858c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './static/media/close-login.80fba7f1f732a18570b0ab99a5755bb6.svg' and @alt = 'logo']</value>
      <webElementGuid>271df20a-d0c8-4b85-a24f-5bfc2348f4d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
