<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Create an account_signuppassword</name>
   <tag></tag>
   <elementGuidId>32ab703b-41b0-47db-aa20-54f04ddc0e64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signuppassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signuppassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a370d87-08dd-4a8c-b155-8828f4bb6e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8e28ce1-2e41-4fbd-b606-65bd8833007a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>f72ae2fe-df8e-4b22-87f7-46568e6206d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-box</value>
      <webElementGuid>09882c9f-cde2-4fc7-b837-0c691e32cb8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signuppassword</value>
      <webElementGuid>e6411b3d-1bf0-48d0-81bb-e0c03300e5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signuppassword&quot;)</value>
      <webElementGuid>0a780c41-5bd0-4984-8140-95e751e63874</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signuppassword']</value>
      <webElementGuid>81348c76-5dc0-46b5-9a9c-972a7366e81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signup_box']/div[3]/label/input</value>
      <webElementGuid>85ce023d-06cc-4d8f-b567-5d9ecdad2e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>3b757a36-f2ba-442d-bde5-091863461e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'signuppassword']</value>
      <webElementGuid>c647dc4c-7add-4d4b-914b-950a9b8f14f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
