<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Create an account_agree_t_c_check</name>
   <tag></tag>
   <elementGuidId>d951e1e3-07b5-4542-9ea0-a575fb06300a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#agree_t_c_check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='agree_t_c_check']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95c319f1-29ad-48f5-a29c-7930f138a583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1ba8b9fd-b724-4568-a946-53a6bd6b9748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check-box</value>
      <webElementGuid>4816e124-daaa-4770-b9a6-3c91e896e790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>agree_t_c_check</value>
      <webElementGuid>f5937dbf-d964-40bc-9756-25c3fb35d6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agree_t_c_check&quot;)</value>
      <webElementGuid>35327ae2-a3cc-4c92-a693-043a9dcbf737</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='agree_t_c_check']</value>
      <webElementGuid>400b63ea-736b-40f2-b4bd-c6b1fbceb227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signup_box']/div[5]/label/input</value>
      <webElementGuid>af11198a-e99b-4273-b158-39c5f38357c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label/input</value>
      <webElementGuid>773ef5c9-b913-4316-a231-876191cd317e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'agree_t_c_check']</value>
      <webElementGuid>09395b93-f919-446a-bdd0-3e531b81ae19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
