<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create an account</name>
   <tag></tag>
   <elementGuidId>2b88cde2-68bf-402b-be7a-9ef1e3df760b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signupButton > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='signupButton']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5b84fccf-68a1-494e-a407-254ddae404c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create an account</value>
      <webElementGuid>e7a02e12-7a64-4df3-9f00-22f000eb62b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signupButton&quot;)/span[1]</value>
      <webElementGuid>6038b25f-f5bb-4764-b13b-058bbb1fda44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='signupButton']/span</value>
      <webElementGuid>9f4ef5c6-cc59-4ed6-a14a-745ef1db38ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/following::span[1]</value>
      <webElementGuid>96c38b6b-2e53-475a-9381-8797a9d4788a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Use'])[1]/following::span[1]</value>
      <webElementGuid>fd5c64a5-bca7-431b-910d-5bc025d71ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popular Services'])[1]/preceding::span[1]</value>
      <webElementGuid>3d809463-73ae-427a-8687-5c1d6ecfc9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button/span</value>
      <webElementGuid>c01377dc-2876-4144-bfe9-0a7c8c85b368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Create an account' or . = 'Create an account')]</value>
      <webElementGuid>c596824d-edb5-453d-ab06-5dfc62def3a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
